// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHldZi0JtJGC6x1JKESxzKMAwhe-r_lZw',
    appId: '1:258582651622:web:d3a8188683694c8f311127',
    messagingSenderId: '258582651622',
    projectId: 'authentification-67fb9',
    authDomain: 'authentification-67fb9.firebaseapp.com',
    storageBucket: 'authentification-67fb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4O0gLDAZb-vbZWPEqwqFg61gFZwF1wOg',
    appId: '1:258582651622:android:0f9e723b171ff0a4311127',
    messagingSenderId: '258582651622',
    projectId: 'authentification-67fb9',
    storageBucket: 'authentification-67fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbhIh1uJHV0_FaXOSSa2a4Hj4IN901NM',
    appId: '1:258582651622:ios:0fcd7f5b78c1566e311127',
    messagingSenderId: '258582651622',
    projectId: 'authentification-67fb9',
    storageBucket: 'authentification-67fb9.firebasestorage.app',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbhIh1uJHV0_FaXOSSa2a4Hj4IN901NM',
    appId: '1:258582651622:ios:0fcd7f5b78c1566e311127',
    messagingSenderId: '258582651622',
    projectId: 'authentification-67fb9',
    storageBucket: 'authentification-67fb9.firebasestorage.app',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHldZi0JtJGC6x1JKESxzKMAwhe-r_lZw',
    appId: '1:258582651622:web:cb52fe93b0e3ecc0311127',
    messagingSenderId: '258582651622',
    projectId: 'authentification-67fb9',
    authDomain: 'authentification-67fb9.firebaseapp.com',
    storageBucket: 'authentification-67fb9.firebasestorage.app',
  );
}
